### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by fullwall** [SNWCreations/Citizens2Legacy#1]
Please follow the Citizens license terms here:
https://github.com/CitizensDev/Citizens2/blob/master/LICENSE#L13

**Comment by SNWCreations** [comment]
Okay! Sorry for the misunderstanding of the license.
I'll do this when I'm free.

**Comment by SNWCreations** [comment]
I've changed the license. Sorry for this issue again!
Please reopen this if you still have comments on this.
